- name: Deploy Kubernetes objects for auth application
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars.yaml

  tasks:
    - name: Create chater-auth Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: chater-auth
    - name: Deploy chater-auth Deployment
      kubernetes.core.k8s:
        state: present
        namespace: chater-auth
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: chater-auth
            namespace: chater-auth
          spec:
            replicas: 2
            selector:
              matchLabels:
                app: chater-auth
            template:
              metadata:
                labels:
                  app: chater-auth
                annotations:
                  co.elastic.logs/enabled: "true"
              spec:
                containers:
                  - name: chater-auth
                    image: singularis314/chater-auth:0.1
                    imagePullPolicy: Always
                    env:
                      - name: EATER_SECRET_KEY
                        valueFrom:
                          secretKeyRef:
                            name: chater-auth
                            key: EATER_SECRET_KEY
                      - name: BOOTSTRAP_SERVERS
                        value: "{{ vars.BOOTSTRAP_SERVER }}"
                affinity:
                  nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                      nodeSelectorTerms:
                        - matchExpressions:
                            - key: kubernetes.io/hostname
                              operator: In
                              values:
                                - racoon
                                - racoon-gpu
    - name: Create secret for environment variables
      kubernetes.core.k8s:
        state: present
        namespace: chater-auth
        kind: Secret
        name: chater-auth
        resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: chater-auth
            namespace: chater-auth
          data:
            EATER_SECRET_KEY: "{{ vars.EATER_SECRET_KEY | b64encode }}"