---
- name: "Main file workload configuration"
  hosts: localhost
  connection: local
  gather_facts: false
- name: Setup chater-gpr-operator
  import_playbook: ./chater-operators/chater-gpt-operator/chater-gpt-operator.yaml
- name: Setup chater_ui
  import_playbook: ./chater_ui/chater_ui.yaml
- name: Setup chater_dlp
  import_playbook: ./chater_dlp/chater_dlp.yaml
- name: Setup creds for DLP
  import_playbook: ./dlp-secret-auth/gcp-dlp-service-account.yaml
- name: Setup chater_gpt
  import_playbook: ./chater_gpt/chater_gpt.yaml
- name: Setup chater_gemini
  import_playbook: ./chater_gemini/chater_gemini.yaml
- name: Setup eater
  import_playbook: ./eater/eater_anisble.yaml
- name: Setup feedback
  import_playbook: ./feedback_service/feedback.yaml