---
- name: "Main file workload configuration"
  hosts: localhost
  connection: local
  gather_facts: false
- name: Setup admin_service
  import_playbook: ./admin_service/admin.yaml
- name: Setup chater_auth
  import_playbook: ./chater_auth/chater_auth.yaml
- name: Setup chater_dlp
  import_playbook: ./chater_dlp/chater_dlp.yaml
- name: Setup creds for DLP
  import_playbook: ./dlp-secret-auth/gcp-dlp-service-account.yaml
- name: Setup chater_gemini
  import_playbook: ./chater_gemini/chater_gemini.yaml
- name: Setup chater_gpt
  import_playbook: ./chater_gpt/chater_gpt.yaml
- name: Setup chater-gpr-operator
  import_playbook: ./chater-operators/chater-gpt-operator/chater-gpt-operator.yaml
- name: Setup chater_ui
  import_playbook: ./chater_ui/chater_ui.yaml
- name: Setup chater_vision
  import_playbook: ./chater-vision/chater_vision.yaml
- name: Setup eater
  import_playbook: ./eater/eater_anisble.yaml
- name: Setup eater_user
  import_playbook: ./eater_user/eater_user.yaml
- name: Setup eater-postgres-mcp
  import_playbook: ./eater-postgres-mcp/eater-postgres-mcp.yaml
- name: Setup load_test
  import_playbook: ./load_test/load_test.yaml
- name: Setup mcpo-proxy
  import_playbook: ./mcpo-proxy/eater-postgres-mcpo-proxy.yaml
- name: Setup models-processor
  import_playbook: ./models_processor/models_processor.yaml