---
- name: "Main file workload configuration"
  hosts: localhost
  connection: local
  gather_facts: false
- name: Setup chater_ui
  import_playbook: ./chater_ui/chater_ui.yaml
- name: Setup chater_dlp
  import_playbook: ./chater_dlp/chater_dlp.yaml
- name: Setup creds for DLP
  import_playbook: ./dlp-secret-auth/gcp-dlp-service-account.yaml
- name: Setup chater_gpt
  import_playbook: ./chater_gpt/chater_gpt.yaml