- name: Deploy Kubernetes objects for vision application
  hosts: localhost
  gather_facts: no

  vars_files:
    - ../vars.yaml

  tasks:
    - name: Create gemini Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: chater-vision
    - name: Deploy chater-vision Deployment
      kubernetes.core.k8s:
        state: present
        namespace: chater-vision
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: chater-vision
            namespace: chater-vision
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: chater-vision
            template:
              metadata:
                labels:
                  app: chater-vision
                annotations:
                  co.elastic.logs/enabled: "true"
              spec:
                containers:
                  - name: chater-vision
                    image: singularis314/chater-vision:0.1
                    imagePullPolicy: Always
                    env:
                      - name: VISION_API_KEY
                        valueFrom:
                          secretKeyRef:
                            name: chater-vision
                            key: VISION_API_KEY
                      - name: BOOTSTRAP_SERVERS
                        value: "{{ vars.BOOTSTRAP_SERVER }}"
    - name: Create secret for environment variables
      kubernetes.core.k8s:
        state: present
        namespace: chater-vision
        kind: Secret
        name: chater-vision
        resource_definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: chater-vision
            namespace: chater-vision
          data:
            VISION_API_KEY: "{{ vars.GEMINI_API_KEY | b64encode }}"