# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alcohol.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\ralcohol.proto\x12\x05\x45\x61ter"X\n\x11\x41lcoholDaySummary\x12\x14\n\x0ctotal_drinks\x18\x01 \x01(\x05\x12\x16\n\x0etotal_calories\x18\x02 \x01(\x05\x12\x15\n\rdrinks_of_day\x18\x03 \x03(\t"b\n\x0c\x41lcoholEvent\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x12\n\ndrink_name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61lories\x18\x04 \x01(\x05\x12\x10\n\x08quantity\x18\x05 \x01(\x05"\x19\n\x17GetAlcoholLatestRequest"K\n\x18GetAlcoholLatestResponse\x12/\n\rtoday_summary\x18\x01 \x01(\x0b\x32\x18.Eater.AlcoholDaySummary">\n\x16GetAlcoholRangeRequest\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t">\n\x17GetAlcoholRangeResponse\x12#\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x13.Eater.AlcoholEvent2\xbc\x01\n\x13\x45\x61terAlcoholService\x12S\n\x10GetAlcoholLatest\x12\x1e.Eater.GetAlcoholLatestRequest\x1a\x1f.Eater.GetAlcoholLatestResponse\x12P\n\x0fGetAlcoholRange\x12\x1d.Eater.GetAlcoholRangeRequest\x1a\x1e.Eater.GetAlcoholRangeResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "alcohol_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _ALCOHOLDAYSUMMARY._serialized_start = 24
    _ALCOHOLDAYSUMMARY._serialized_end = 112
    _ALCOHOLEVENT._serialized_start = 114
    _ALCOHOLEVENT._serialized_end = 212
    _GETALCOHOLLATESTREQUEST._serialized_start = 214
    _GETALCOHOLLATESTREQUEST._serialized_end = 239
    _GETALCOHOLLATESTRESPONSE._serialized_start = 241
    _GETALCOHOLLATESTRESPONSE._serialized_end = 316
    _GETALCOHOLRANGEREQUEST._serialized_start = 318
    _GETALCOHOLRANGEREQUEST._serialized_end = 380
    _GETALCOHOLRANGERESPONSE._serialized_start = 382
    _GETALCOHOLRANGERESPONSE._serialized_end = 444
    _EATERALCOHOLSERVICE._serialized_start = 447
    _EATERALCOHOLSERVICE._serialized_end = 635
# @@protoc_insertion_point(module_scope)
