# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: custom_date_food.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'custom_date_food.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ustom_date_food.proto\x12\x05\x65\x61ter\"%\n\x15\x43ustomDateFoodRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\x80\x01\n\x16\x43ustomDateFoodResponse\x12$\n\x0f\x64ishes_for_date\x18\x01 \x03(\x0b\x32\x0b.eater.Dish\x12)\n\rtotal_for_day\x18\x02 \x01(\x0b\x32\x12.eater.TotalForDay\x12\x15\n\rperson_weight\x18\x03 \x01(\x02\"\x9f\x01\n\x04\x44ish\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x11\n\tdish_name\x18\x02 \x01(\t\x12\x1e\n\x16\x65stimated_avg_calories\x18\x03 \x01(\x05\x12\x13\n\x0bingredients\x18\x04 \x03(\t\x12\x18\n\x10total_avg_weight\x18\x05 \x01(\x05\x12\x15\n\rhealth_rating\x18\x06 \x01(\x05\x12\x10\n\x08image_id\x18\x07 \x01(\t\"P\n\x08\x43ontains\x12\x15\n\rcarbohydrates\x18\x01 \x01(\x01\x12\x0c\n\x04\x66\x61ts\x18\x02 \x01(\x01\x12\x10\n\x08proteins\x18\x03 \x01(\x01\x12\r\n\x05sugar\x18\x04 \x01(\x01\"b\n\x0bTotalForDay\x12!\n\x08\x63ontains\x18\x01 \x01(\x0b\x32\x0f.eater.Contains\x12\x18\n\x10total_avg_weight\x18\x02 \x01(\x05\x12\x16\n\x0etotal_calories\x18\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'custom_date_food_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CUSTOMDATEFOODREQUEST']._serialized_start=33
  _globals['_CUSTOMDATEFOODREQUEST']._serialized_end=70
  _globals['_CUSTOMDATEFOODRESPONSE']._serialized_start=73
  _globals['_CUSTOMDATEFOODRESPONSE']._serialized_end=201
  _globals['_DISH']._serialized_start=204
  _globals['_DISH']._serialized_end=363
  _globals['_CONTAINS']._serialized_start=365
  _globals['_CONTAINS']._serialized_end=445
  _globals['_TOTALFORDAY']._serialized_start=447
  _globals['_TOTALFORDAY']._serialized_end=545
# @@protoc_insertion_point(module_scope)
