# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_language.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12set_language.proto\x12\x05\x45\x61ter"?\n\x12SetLanguageRequest\x12\x12\n\nuser_email\x18\x01 \x01(\t\x12\x15\n\rlanguage_code\x18\x02 \x01(\t"&\n\x13SetLanguageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "set_language_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _SETLANGUAGEREQUEST._serialized_start = 29
    _SETLANGUAGEREQUEST._serialized_end = 92
    _SETLANGUAGERESPONSE._serialized_start = 94
    _SETLANGUAGERESPONSE._serialized_end = 132
# @@protoc_insertion_point(module_scope)
