# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: delete_food.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x64\x65lete_food.proto\x12\x05\x45\x61ter"!\n\x11\x44\x65leteFoodRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03"%\n\x12\x44\x65leteFoodResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32Q\n\x0c\x45\x61terService\x12\x41\n\nDeleteFood\x12\x18.Eater.DeleteFoodRequest\x1a\x19.Eater.DeleteFoodResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "delete_food_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _DELETEFOODREQUEST._serialized_start = 28
    _DELETEFOODREQUEST._serialized_end = 61
    _DELETEFOODRESPONSE._serialized_start = 63
    _DELETEFOODRESPONSE._serialized_end = 100
    _EATERSERVICE._serialized_start = 102
    _EATERSERVICE._serialized_end = 183
# @@protoc_insertion_point(module_scope)
