# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: eater_photo.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11\x65\x61ter_photo.proto\x12\x05\x65\x61ter"C\n\x0cPhotoMessage\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x12\n\nphoto_data\x18\x02 \x01(\x0c\x12\x11\n\tphotoType\x18\x03 \x01(\tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "eater_photo_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _PHOTOMESSAGE._serialized_start = 28
    _PHOTOMESSAGE._serialized_end = 95
# @@protoc_insertion_point(module_scope)
