# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feedback.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x66\x65\x65\x64\x62\x61\x63k.proto\x12\x05\x45\x61ter"D\n\x0f\x46\x65\x65\x64\x62\x61\x63kRequest\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x11\n\tuserEmail\x18\x02 \x01(\t\x12\x10\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x03 \x01(\t"#\n\x10\x46\x65\x65\x64\x62\x61\x63kResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32T\n\x0f\x46\x65\x65\x64\x62\x61\x63kService\x12\x41\n\x0eSubmitFeedback\x12\x16.Eater.FeedbackRequest\x1a\x17.Eater.FeedbackResponseb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "feedback_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _FEEDBACKREQUEST._serialized_start = 25
    _FEEDBACKREQUEST._serialized_end = 93
    _FEEDBACKRESPONSE._serialized_start = 95
    _FEEDBACKRESPONSE._serialized_end = 130
    _FEEDBACKSERVICE._serialized_start = 132
    _FEEDBACKSERVICE._serialized_end = 216
# @@protoc_insertion_point(module_scope)
