# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: food_health_level.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66ood_health_level.proto\"9\n\x16\x46oodHealthLevelRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x11\n\tfood_name\x18\x02 \x01(\t\"U\n\x17\x46oodHealthLevelResponse\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x16\n\x0ehealth_summary\x18\x03 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'food_health_level_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOODHEALTHLEVELREQUEST._serialized_start=27
  _FOODHEALTHLEVELREQUEST._serialized_end=84
  _FOODHEALTHLEVELRESPONSE._serialized_start=86
  _FOODHEALTHLEVELRESPONSE._serialized_end=171
# @@protoc_insertion_point(module_scope)
