# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_recomendation.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x17get_recomendation.proto\x12\x05\x65\x61ter"%\n\x15RecommendationRequest\x12\x0c\n\x04\x64\x61ys\x18\x01 \x01(\x05"0\n\x16RecommendationResponse\x12\x16\n\x0erecommendation\x18\x01 \x01(tb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "get_recomendation_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _RECOMMENDATIONREQUEST._serialized_start = 34
    _RECOMMENDATIONREQUEST._serialized_end = 71
    _RECOMMENDATIONRESPONSE._serialized_start = 73
    _RECOMMENDATIONRESPONSE._serialized_end = 121
# @@protoc_insertion_point(module_scope)
