# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manual_weight.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13manual_weight.proto\x12\x05\x45\x61ter"9\n\x13ManualWeightRequest\x12\x0e\n\x06weight\x18\x01 \x01(\x02\x12\x12\n\nuser_email\x18\x02 \x01(\t"\'\n\x14ManualWeightResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manual_weight_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MANUALWEIGHTREQUEST._serialized_start=30
  _MANUALWEIGHTREQUEST._serialized_end=87
  _MANUALWEIGHTRESPONSE._serialized_start=89
  _MANUALWEIGHTRESPONSE._serialized_end=128
# @@protoc_insertion_point(module_scope)
