# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modify_food_record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18modify_food_record.proto\x12\x05\x45\x61ter"O\n\x17ModifyFoodRecordRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x12\n\nuser_email\x18\x02 \x01(\t\x12\x12\n\npercentage\x18\x03 \x01(\x05"+\n\x18ModifyFoodRecordResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "modify_food_record_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _MODIFYFOODRECORDREQUEST._serialized_start = 35
    _MODIFYFOODRECORDREQUEST._serialized_end = 114
    _MODIFYFOODRECORDRESPONSE._serialized_start = 116
    _MODIFYFOODRECORDRESPONSE._serialized_end = 159
# @@protoc_insertion_point(module_scope)
