---
- name: "Main chater"
  hosts: localhost
  connection: local
  gather_facts: no
- name: Import postgres
  import_playbook: ./postgres_eater.yaml
- name: Import eater
  import_playbook: ./eater.yaml