---
- name: Apply PostgreSQL Custom Resource
  hosts: localhost
  gather_facts: no
  vars_files:
    - ../vars.yaml
  tasks:
    - name: Apply PostgreSQL CRD
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: "acid.zalan.do/v1"
          kind: "postgresql"
          metadata:
            name: "eater-db"
            namespace: "eater"
            labels:
              team: acid
          spec:
            teamId: "acid"
            postgresql:
              version: "16"
            numberOfInstances: 2
            maintenanceWindows: []
            volume:
              size: "10Gi"
            users:
              eater: []
            databases:
              eater: eater
            allowedSourceRanges:
              - 0.0.0.0/32
            resources:
              requests:
                cpu: "100m"
                memory: "100Mi"
              limits:
                cpu: "500m"
                memory: "500Mi"
            patroni:
              initdb:
                encoding: UTF8
                data-checksums: "true"
            podAnnotations: {}
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 100
                  podAffinityTerm:
                    labelSelector:
                      matchExpressions:
                        - key: cluster-name
                          operator: In
                          values:
                            - eater-db
                    topologyKey: kubernetes.io/hostname
            tolerations:
              - key: gpu-only
                operator: Equal
                value: "true"
                effect: NoSchedule
      register: result
    - name: Create local directory for eater-postgres
      ansible.builtin.file:
        path: /other/eater_postgres
        state: directory
        mode: '0777'
      delegate_to: racoon
      become: true
      vars:
        ansible_become_password: "{{ ansible_become_password_racoon }}"
    - name: Create local directory for eater-postgres on racoon-gpu
      ansible.builtin.file:
        path: /other/eater_postgres
        state: directory
        mode: '0777'
      delegate_to: racoon-gpu
      become: true
      vars:
        ansible_become_password: "{{ ansible_become_password_gpu }}"
    - name: Create eater_postgres PersistentVolume
      kubernetes.core.k8s:
        state: present
        namespace: eater
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: eater-postgres-pvc
            namespace: eater
          spec:
            capacity:
              storage: 10Gi
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Recycle
            local:
              path: /other/eater_postgres
            nodeAffinity:
              required:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "racoon"
    - name: Create eater_postgres PersistentVolume (racoon-gpu)
      kubernetes.core.k8s:
        state: present
        namespace: eater
        definition:
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: eater-postgres-pvc-gpu
            namespace: eater
          spec:
            capacity:
              storage: 10Gi
            volumeMode: Filesystem
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Recycle
            local:
              path: /other/eater_postgres
            nodeAffinity:
              required:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - "racoon-gpu"