# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/add_friend.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "proto/add_friend.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16proto/add_friend.proto\x12\x05\x45\x61ter"!\n\x10\x41\x64\x64\x46riendRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t"$\n\x11\x41\x64\x64\x46riendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.add_friend_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_ADDFRIENDREQUEST"]._serialized_start = 33
    _globals["_ADDFRIENDREQUEST"]._serialized_end = 66
    _globals["_ADDFRIENDRESPONSE"]._serialized_start = 68
    _globals["_ADDFRIENDRESPONSE"]._serialized_end = 104
# @@protoc_insertion_point(module_scope)
