# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: add_friend.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61\x64\x64_friend.proto\x12\x05\x45\x61ter\"!\n\x10\x41\x64\x64\x46riendRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"$\n\x11\x41\x64\x64\x46riendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'add_friend_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ADDFRIENDREQUEST._serialized_start=27
  _ADDFRIENDREQUEST._serialized_end=60
  _ADDFRIENDRESPONSE._serialized_start=62
  _ADDFRIENDRESPONSE._serialized_end=98
# @@protoc_insertion_point(module_scope)
