# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_friends.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11get_friends.proto\x12\x05\x45\x61ter\"\x13\n\x11GetFriendsRequest\")\n\x06\x46riend\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\"C\n\x12GetFriendsResponse\x12\x1e\n\x07\x66riends\x18\x01 \x03(\x0b\x32\r.Eater.Friend\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'get_friends_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETFRIENDSREQUEST._serialized_start=28
  _GETFRIENDSREQUEST._serialized_end=47
  _FRIEND._serialized_start=49
  _FRIEND._serialized_end=90
  _GETFRIENDSRESPONSE._serialized_start=92
  _GETFRIENDSRESPONSE._serialized_end=159
# @@protoc_insertion_point(module_scope)
