# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/get_friends.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/get_friends.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/get_friends.proto\x12\x05\x45\x61ter\"\x13\n\x11GetFriendsRequest\"\x17\n\x06\x46riend\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"C\n\x12GetFriendsResponse\x12\x1e\n\x07\x66riends\x18\x01 \x03(\x0b\x32\r.Eater.Friend\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.get_friends_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETFRIENDSREQUEST']._serialized_start=34
  _globals['_GETFRIENDSREQUEST']._serialized_end=53
  _globals['_FRIEND']._serialized_start=55
  _globals['_FRIEND']._serialized_end=78
  _globals['_GETFRIENDSRESPONSE']._serialized_start=80
  _globals['_GETFRIENDSRESPONSE']._serialized_end=147
# @@protoc_insertion_point(module_scope)
