# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: share_food.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10share_food.proto\x12\x05\x45\x61ter\"Z\n\x10ShareFoodRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x12\n\nfrom_email\x18\x02 \x01(\t\x12\x10\n\x08to_email\x18\x03 \x01(\t\x12\x12\n\npercentage\x18\x04 \x01(\x05\";\n\x11ShareFoodResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rnickname_used\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'share_food_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SHAREFOODREQUEST._serialized_start=27
  _SHAREFOODREQUEST._serialized_end=117
  _SHAREFOODRESPONSE._serialized_start=119
  _SHAREFOODRESPONSE._serialized_end=178
# @@protoc_insertion_point(module_scope)
