# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/share_food.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "proto/share_food.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16proto/share_food.proto\x12\x05\x45\x61ter"Z\n\x10ShareFoodRequest\x12\x0c\n\x04time\x18\x01 \x01(\x03\x12\x12\n\nfrom_email\x18\x02 \x01(\t\x12\x10\n\x08to_email\x18\x03 \x01(\t\x12\x12\n\npercentage\x18\x04 \x01(\x05"$\n\x11ShareFoodResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.share_food_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SHAREFOODREQUEST"]._serialized_start = 33
    _globals["_SHAREFOODREQUEST"]._serialized_end = 123
    _globals["_SHAREFOODRESPONSE"]._serialized_start = 125
    _globals["_SHAREFOODRESPONSE"]._serialized_end = 161
# @@protoc_insertion_point(module_scope)
